-- Run once in Supabase SQL editor before using VIP Meeting scheduling.
create table if not exists public.vip_meetings (
  id bigint generated by default as identity primary key,
  guest_name text not null,
  guest_email text not null,
  guest_phone text,
  notes text,
  scheduled_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamptz not null default now()
);

create unique index if not exists vip_meetings_scheduled_at_active_idx
  on public.vip_meetings (scheduled_at)
  where (status <> 'cancelled');

create index if not exists vip_meetings_scheduled_at_idx
  on public.vip_meetings (scheduled_at);

alter table public.vip_meetings enable row level security;

-- PostgreSQL does not support "create policy if not exists"; drop then recreate for idempotency.
drop policy if exists "vip_meetings_select_public" on public.vip_meetings;
create policy "vip_meetings_select_public"
  on public.vip_meetings for select
  using (true);

drop policy if exists "vip_meetings_insert_public" on public.vip_meetings;
create policy "vip_meetings_insert_public"
  on public.vip_meetings for insert
  with check (true);

drop policy if exists "vip_meetings_update_public" on public.vip_meetings;
create policy "vip_meetings_update_public"
  on public.vip_meetings for update
  using (true);

drop policy if exists "vip_meetings_delete_public" on public.vip_meetings;
create policy "vip_meetings_delete_public"
  on public.vip_meetings for delete
  using (true);

-- Admin-editable availability (weekly hours, blocked dates, slot length).
create table if not exists public.vip_meeting_settings (
  id int primary key default 1 check (id = 1),
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.vip_meeting_settings (id, settings)
values (1, '{}'::jsonb)
on conflict (id) do nothing;

alter table public.vip_meeting_settings enable row level security;

drop policy if exists "vip_meeting_settings_select_public" on public.vip_meeting_settings;
create policy "vip_meeting_settings_select_public"
  on public.vip_meeting_settings for select
  using (true);

drop policy if exists "vip_meeting_settings_insert_public" on public.vip_meeting_settings;
create policy "vip_meeting_settings_insert_public"
  on public.vip_meeting_settings for insert
  with check (true);

drop policy if exists "vip_meeting_settings_update_public" on public.vip_meeting_settings;
create policy "vip_meeting_settings_update_public"
  on public.vip_meeting_settings for update
  using (true);
